<?php
require_once './sites/all/libraries/FoursquareUtil.php';

function burgergdl_node_view($node, $view_mode, $langcode){
  $type = $node->type;
  if($type!="restaurant"){return;}
  $venue_id = $node->field_foursquare_id['und'][0]['value'];
  
  $util = new FoursquareUtil();
  $photos = $util->get_photos($venue_id);
  $node->photos = $photos;
  
  //drupal_set_message(drupal_get_path('module', 'burgergdl'));
}


function burgergdl_theme($existing, $type, $theme, $path) {
  $items = array(
    'node__restaurant' => array(
      // Don't specify the path in the template name.
      // Unless you have your template inside a directory within this module.
      'template' =>  'node--restaurant',
      'variables' => array('node' => (object)array()),
      // If you want to put the tpl in another location, you can use this key.
      'theme path' => drupal_get_path('module', 'burgergdl'),
    ),
  );
  return $items;
}